### ISSUE TITLE
responsive problem in orientation portrait iframe

### ISSUE THREAD

**Issue by kakamband** [suconghou/ustream#1]
Hi suconghou,
please fix responsive in orientation portrait iframe , see this problem in action :
https://gist.github.com/kakamband/806ed34ab5ad1c3f5edf852ecdebcdd5
after save above code in html file & run in browser , change Responsive Design Mode ( Ctrl+ Shift+ M) & see the responsive problem in orientation portrait iframe 
waiting for your response
finest regards

**Comment by suconghou** [comment]
click fullscreen button to view in landscape mode instead of rotate the elements

**Comment by kakamband** [comment]
Hi suconghou,
I need to show iframe in orientation portrait for mobile devices user agents
can you help me to solve this problem ?
waiting for your response
finest regards
