### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by dfmjndm** [suconghou/ustream#3]
视频显示CACHE is not defined，其余信息均显示完整，视频解析通过worker部署
![image](https://user-images.githubusercontent.com/57401901/154291284-fb539636-bd89-4f80-8663-9e5a2938fa65.png)

**Comment by suconghou** [comment]
设置- KV 命名空间绑定
绑定一个 CACHE的KV命名空间

**Comment by dfmjndm** [comment]
> 设置- KV 命名空间绑定 绑定一个 CACHE的KV命名空间

![image](https://user-images.githubusercontent.com/57401901/154743472-a0aacb23-b052-4a04-975b-150ec35e0e99.png)
额，变成了这个

**Comment by dfmjndm** [comment]
感谢，已解决
